name: labeled

on:
  pull_request_target:
    types: [labeled]

jobs:
  labeled:
    name: labeled
    runs-on: ubuntu-latest
    steps:
      - run: echo pull_request_target labeled

      - run: echo ${{ github.ref_name }}
      - run: echo "${{ toJson(github) }}"
