name: synchronize

on:
  pull_request_target:
    types: [synchronize]

jobs:
  synchronize:
    name: synchronize
    runs-on: ubuntu-latest
    steps:
      - run: echo pull_request_target synchronize

      - run: echo ${{ github.ref_name }}
      - run: echo "${{ toJson(github) }}"
