name: unassigned

on:

  pull_request_target:
    types: [unassigned]

jobs:
  unassigned:
    name: unassigned
    runs-on: ubuntu-latest
    steps:
      - run: echo pull_request_target unassigned

      - run: echo ${{ gitverse.ref_name }}
      - run: echo "${{ toJson(gitverse) }}"
